---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@b75144d1e56db571800343c03f7e7f1cda8a8e52
    secrets: inherit
