---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@b75144d1e56db571800343c03f7e7f1cda8a8e52
    secrets: inherit
