---
name: PR commented

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types:
      - created

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_comment_dispatch_callable.yml@b75144d1e56db571800343c03f7e7f1cda8a8e52
    secrets: inherit
