---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@b75144d1e56db571800343c03f7e7f1cda8a8e52
    secrets: inherit
